name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  publish_crate:
    name: Publish crate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Publish to crates.io
        run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

  publish_release:
    name: Publish release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
